const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    // //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USE_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAIDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAIDED',

    //luuuser
    CREATE_USER_SUCCSESS: 'CREATE_USER_SUCCSESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAIDED',

    //alluser
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAIDED',

    //xoauser
    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILDED: 'DELETE_USERS_FAIDED',

    //edituser
    EDIT_USERS_SUCCESS: 'EDIT_USERS_SUCCESS',
    EDIT_USERS_FAILDED: 'EDIT_USERS_FAIDED',
    //topdanhmuc
    FETCH_ALL_NV_SUCCESS: 'FETCH_ALL_NV_SUCCESS',
    FETCH_ALL_NV_FAILDED: 'FETCH_ALL_NV_FAILDED',
    ///////////////////////////////
    ///////////////////////////////
    ///////////danh muc////////////
    ///////////////////////////////
    ///all danh muc
    FETCH_ALL_DANHMUC_SUCCESS: 'FETCH_ALL_DANHMUC_SUCCESS',
    FETCH_ALL_DANHMUC_FAILDED: 'FETCH_ALL_DANHMUC_FAIDED',
    ///luudanhmuc
    CREATE_DANHMUC_SUCCSESS: 'CREATE_DANHMUC_SUCCSESS',
    CREATE_DANHMUC_FAILDED: 'CREATE_DANHMUC_FAIDED',
    /// xoa danh muc
    DELETE_DANHMUC_SUCCESS: 'DELETE_DANHMUC_SUCCESS',
    DELETE_DANHMUC_FAILDED: 'DELETE_DANHMUC_FAILDED',
    // edit danh muc
    EDIT_DANHMUC_SUCCESS: 'EDIT_DANHMUC_SUCCESS',
    EDIT_DANHMUC_FAILDED: 'EDIT_DANHMUC_FAILDED',
    //topdanhmuc
    FETCH_TOP_DANHMUC_SUCCESS: 'FETCH_TOP_DANHMUC_SUCCESS',
    FETCH_TOP_DANHMUC_FAILDED: 'FETCH_TOP_DANHMUC_FAIDED',
    ///////////////////////////////
    ///////////loai su kien////////
    ///////////////////////////////
    ///all loai sk
    FETCH_ALL_LOAISK_SUCCESS: 'FETCH_ALL_LOAISK_SUCCESS',
    FETCH_ALL_LOAISK_FAILDED: 'FETCH_ALL_LOAISK_FAIDED',
    ///luuloaisk
    CREATE_LOAISK_SUCCSESS: 'CREATE_LOAISK_SUCCSESS',
    CREATE_LOAISK_FAILDED: 'CREATE_LOAISK_FAIDED',
    //topsk
    FETCH_TOP_LOAISK_SUCCESS: 'FETCH_TOP_LOAISK_SUCCESS',
    FETCH_TOP_LOAISK_FAILDED: 'FETCH_TOP_LOAISK_FAIDED',
    //all su kien
    FETCH_ALL_SUKIEN_SUCCESS: 'FETCH_ALL_SUKIEN_SUCCESS',
    FETCH_ALL_SUKIEN_FAILDED: 'FETCH_ALL_SUKIEN_FAIDED',

    ///create info su kien
    FETCH_INFO_SUKIEN_SUCCESS: 'FETCH_INFO_SUKIEN_SUCCESS',
    FETCH_INFO_SUKIEN_FAILDED: 'FETCH_INFO_SUKIEN_FAILDED',

    ///////////////////////////////
    ///////////size////////
    ///////////////////////////////
    FETCH_ALL_SIZE_SUCCESS: 'FETCH_ALL_SIZE_SUCCESS',
    FETCH_ALL_SIZE_FAILDED: 'FETCH_ALL_SIZE_FAIDED',
    ///////////////////////////////
    ///////////size////////
    ///////////////////////////////
    ///save mon
    CREATE_MON_SUCCESS: 'CREATE_MON_SUCCESS',
    CREATE_MON_FAILDED: 'CREATE_MON_FAILDED',
    ///all mon
    FETCH_ALL_MON_SUCCESS: 'FETCH_ALL_MON_SUCCESS',
    FETCH_ALL_MON_FAILDED: 'FETCH_ALL_MON_FAILDED',
    ///edit mon
    EDIT_MON_SUCCESS: 'EDIT_MON_SUCCESS',
    EDIT_MON_FAILDED: 'EDIT_MON_FAILDED',
    ///xoa mon
    DELETE_MON_SUCCESS: 'DELETE_MON_SUCCESS',
    DELETE_MON_FAILDED: 'DELETE_MON_FAILDED',
    ///save gia mon
    CREATE_GIA_MON_SUCCESS: 'CREATE_GIA_MON_SUCCESS',
    CREATE_GIA_MON_FAILDED: 'CREATE_GIA_MON_FAILDED',
    ///alll gia mon
    FETCH_ALL_GIA_MON_SUCCESS: 'FETCH_ALL_GIA_MON_SUCCESS',
    FETCH_ALL_GIA_MON_FAILDED: 'FETCH_ALL_GIA_MON_FAILDED',
    ///xoa gia mon
    DELETE_GIA_MON_SUCCESS: 'DELETE_GIA_MON_SUCCESS',
    DELETE_GIA_MON_FAILDED: 'DELETE_GIA_MON_FAILDED',
    ///edit mon
    EDIT_GIA_MON_SUCCESS: 'EDIT_GIA_MON_SUCCESS',
    EDIT_GIA_MON_FAILDED: 'EDIT_GIA_MON_FAILDED',
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////khu ban//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /// all khu
    FETCH_ALL_KHU_SUCCESS: 'FETCH_ALL_KHU_SUCCESS',
    FETCH_ALL_KHU_FAILDED: 'FETCH_ALL_KHU_FAILDED',
    /// create khu 
    CREATE_KHU_SUCCESS: 'CREATE_KHU_SUCCESS',
    CREATE_KHU_FAILDED: 'CREATE_KHU_FAILDED',
    /// edit khu
    EDIT_KHU_SUCCESS: 'EDIT_KHU_SUCCESS',
    EDIT_KHU_FAILDED: 'EDIT_KHU_FAILDED',
    /// delete khu
    DELETE_KHU_SUCCESS: 'DELETE_KHU_SUCCESS',
    DELETE_KHU_FAILDED: 'DELETE_KHU_FAILDED',
    /// all ban
    FETCH_ALL_BAN_SUCCESS: 'FETCH_ALL_BAN_SUCCESS',
    FETCH_ALL_BAN_FAILDED: 'FETCH_ALL_BAN_FAILDED',
    /// create ban 
    CREATE_BAN_SUCCESS: 'CREATE_BAN_SUCCESS',
    CREATE_BAN_FAILDED: 'CREATE_BAN_FAILDED',
    /// edit ban
    EDIT_BAN_SUCCESS: 'EDIT_BAN_SUCCESS',
    EDIT_BAN_FAILDED: 'EDIT_BAN_FAILDED',
    /// delete ban
    DELETE_BAN_SUCCESS: 'DELETE_BAN_SUCCESS',
    DELETE_BAN_FAILDED: 'DELETE_BAN_FAILDED',
    //all time
    FETCH_TIME_SUCCESS: 'FETCH_TIME_SUCCESS',
    FETCH_TIME_FAILDED: 'FETCH_TIME_FAILDED',
    /// xoa su kien
    DELETE_SK_SUCCESS: 'DELETE_SK_SUCCESS',
    DELETE_SK_FAILDED: 'DELETE_SK_FAILDED',
    // edit sk
    EDIT_SK_SUCCESS: 'EDIT_SK_SUCCESS',
    EDIT_SK_FAILDED: 'EDIT_SK_FAILDED',
    // all giá sk
    FETCH_ALL_GIA_SK_SUCCESS: 'FETCH_ALL_GIA_SK_SUCCESS',
    FETCH_ALL_GIA_SK_FAILDED: 'FETCH_ALL_GIA_SK_FAILDED',
    // all giá pttt
    FETCH_ALL_PTTTT_SUCCESS: 'FETCH_ALL_PTTTT_SUCCESS',
    FETCH_ALL_PTTTT_FAILDED: 'FETCH_ALL_PTTTT_FAILDED',
    //// get cart by id
    FETCH_ALL_CART_BYID_SUCCESS: 'FETCH_ALL_CART_BYID_SUCCESS',
    FETCH_ALL_CART_BYID_FAILDED: 'FETCH_ALL_CART_BYID_FAILDED',
    //all status
    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILDED: 'FETCH_STATUS_FAILDED',
    /// edit ban
    EDIT_STATUSS_SUCCESS: 'EDIT_STATUSS_SUCCESS',
    EDIT_STATUSS_FAILDED: 'EDIT_STATUSS_FAILDED',
    /// edit ban
    EDIT_YCHD_SUCCESS: 'EDIT_YCHD_SUCCESS',
    EDIT_YCHD_FAILDED: 'EDIT_YCHD_FAILDED',
    //all nhan vien
    FETCH_NHANVIEN_SUCCESS: 'FETCH_NHANVIEN_SUCCESS',
    FETCH_NHANVIEN_FAILDED: 'FETCH_NHANVIEN_FAILDED',
    /// create ban 
    CREATE_PHIEUCHI_SUCCESS: 'CREATE_PHIEUCHI_SUCCESS',
    CREATE_PHIEUCHI_FAILDED: 'CREATE_PHIEUCHI_FAILDED',
    //all phieu chi
    FETCH_PHIEUCHI_SUCCESS: 'FETCH_PHIEUCHI_SUCCESS',
    FETCH_PHIEUCHI_FAILDED: 'FETCH_PHIEUCHI_FAILDED',
    /// xoa phieu chi
    DELETE_PHIEUCHI_SUCCESS: 'DELETE_PHIEUCHI_SUCCESS',
    DELETE_PHIEUCHI_FAILDED: 'DELETE_PHIEUCHI_FAILDED',
    /// edit ban
    EDIT_PHIEUCHI_SUCCESS: 'EDIT_PHIEUCHI_SUCCESS',
    EDIT_PHIEUCHI_FAILDED: 'EDIT_PHIEUCHI_FAILDED',
    /// tt bàn
    FETCH_STA_SUCCESS: 'FETCH_STA_SUCCESS',
    FETCH_STA_FAILDED: 'FETCH_STA_FAILDED',

    /// all ghe
    FETCH_ALL_GHE_SUCCESS: 'FETCH_ALL_GHE_SUCCESS',
    FETCH_ALL_GHE_FAILDED: 'FETCH_ALL_GHE_FAILDED',
    /// create ghe 
    CREATE_GHE_SUCCESS: 'CREATE_GHE_SUCCESS',
    CREATE_GHE_FAILDED: 'CREATE_GHE_FAILDED',
    /// edit ghe
    EDIT_GHE_SUCCESS: 'EDIT_GHE_SUCCESS',
    EDIT_GHE_FAILDED: 'EDIT_GHE_FAILDED',
    /// delete ghe
    DELETE_GHE_SUCCESS: 'DELETE_GHE_SUCCESS',
    DELETE_GHE_FAILDED: 'DELETE_GHE_FAILDED',
    //all status ve
    FETCH_STATUSVE_SUCCESS: 'FETCH_STATUSVE_SUCCESS',
    FETCH_STATUSVE_FAILDED: 'FETCH_STATUSVE_FAILDED',
    //update tt vé
    EDIT_STATUSSVE_SUCCESS: 'EDIT_STATUSSVE_SUCCESS',
    EDIT_STATUSSVE_FAILDED: 'EDIT_STATUSSVE_FAILDED',
})


export default actionTypes